# Generated by Django 2.2.6 on 2019-11-27 16:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(default=None, max_length=200)),
                ('user_phone', models.CharField(max_length=10)),
                ('user_address', models.CharField(blank=True, max_length=100)),
                ('user_city', models.CharField(blank=True, max_length=50)),
                ('user_zipcode', models.CharField(blank=True, max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('registery', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('final', models.IntegerField(default=0)),
                ('invoice_id', models.IntegerField(default=0)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property_purchased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.PropertyListing')),
            ],
        ),
    ]
