# Generated by Django 2.2.6 on 2019-12-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='Verify',
            field=models.CharField(choices=[('V', 'Verified'), ('N', 'Not Verified')], default='N', max_length=1),
        ),
    ]
