# Generated by Django 2.2.6 on 2019-12-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertylisting_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='Verify',
            field=models.CharField(choices=[('V', 'Verified'), ('N', 'Not Verified'), ('R', 'rejected')], default='N', max_length=1),
        ),
    ]
